### ISSUE TITLE
Is it possible to cache `docker-php-ext-configure` commands?

### ISSUE THREAD

**Issue by marcoarruda** [rrd108/cakephp-bitbucket-pipelines-examples#1]
Is it possible to cache `docker-php-ext-configure` commands?

It takes few minutes to finish (which is too much for a pipeline), could it be improved by caching it somehow?

**Comment by rrd108** [comment]
That is a good question, but I do not really know...

**Comment by marcoarruda** [comment]
Yet can't answer, but I managed using a `ready-to-use` cakephp image:

[jorgegonzalezcakedc/cakephp-runner](https://hub.docker.com/r/jorgegonzalezcakedc/cakephp-runner)

Which saved me almost **3 minutes** for each pipeline that is run.
The `yml` got similar to below:

```
image: jorgegonzalezcakedc/cakephp-runner

pipelines:
  pull-requests:
    "**":
      - step:
          caches:
            - composer
          script:
            - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
            - composer install
            - vendor/bin/phpunit
          services:
            - mysql

definitions:
  services:
    mysql:
      image: mysql:5.7
      environment:
        MYSQL_DATABASE: db
        MYSQL_RANDOM_ROOT_PASSWORD: "yes"
        MYSQL_USER: user
        MYSQL_PASSWORD: pass
```
